deb support

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -746,6 +746,46 @@ write_pkginfo() {
 	write_kv_pair "checkdepend" "${checkdepends[@]}"
 }
 
+write_deb_control() {
+	local size=$(dirsize)
+
+	merge_arch_attrs
+
+	echo "Package: $pkgname"
+	echo "Essential: no"
+	echo "Priority: required"
+#  echo "Maintainer: $(head)"
+
+	local fullver=$(get_full_version)
+	echo "Version: $fullver"
+
+# TODO: all fields should have this treatment
+	local spd="${pkgdesc//+([[:space:]])/ }"
+	spd=("${spd[@]#[[:space:]]}")
+	spd=("${spd[@]%[[:space:]]}")
+
+	echo "Description: $spd"
+	echo "Homepage: $url"
+	echo "Builddate: $SOURCE_DATE_EPOCH"
+	echo "Maintainer: $PACKAGER"
+	echo "Installed-Size: $size"
+	echo "Arch: $pkgarch"
+
+	mapfile -t provides < <(find_libprovides)
+	mapfile -t depends < <(find_libdepends)
+
+	echo "License: ${license[@]}"
+	echo "Replaces: ${replaces[@]}"
+#	echo "group: ${groups[@]}"
+	echo "Conflicts: ${conflicts[@]}"
+	echo "Provides: ${provides[@]}"
+#	echo "backup: ${backup[@]}"
+	echo "Pre-Depends: ${depends[@]}"
+	echo "Suggests: ${optdepends[@]//+([[:space:]])/ }"
+	echo "Built-Using: ${makedepends[@]}"
+#	echo "checkdepend: ${checkdepends[@]}"
+}
+
 write_buildinfo() {
 	write_kv_pair "format" "2"
 
@@ -800,6 +840,71 @@ find_distro() {
 
 create_package() {
   create_package_$(echo $distro | cut -f1 -d -)
+}
+
+create_package_debian() {
+{
+	(( NOARCHIVE )) && return 0
+
+	if [[ ! -d $pkgdir ]]; then
+		error "$(gettext "Missing %s directory.")" "\$pkgdir/"
+		plainerr "$(gettext "Aborting...")"
+		exit $E_MISSING_PKGDIR
+	fi
+
+	cd_safe "$pkgdir"
+	msg "$(gettext "Creating package \"%s\"...")" "$pkgname"
+
+	pkgarch=$(get_pkg_arch)
+	msg2 "$(gettext "Generating %s file...")" "debian/control"
+  mkdir -p DEBIAN
+	write_deb_control > DEBIAN/control
+#	msg2 "$(gettext "Generating %s file...")" ".BUILDINFO"
+#	write_buildinfo > .BUILDINFO
+
+	# check for changelog/install files
+#	for i in 'install/.INSTALL'; do
+#		IFS='/' read -r orig dest < <(printf '%s\n' "$i")
+
+#		if [[ -n ${!orig} ]]; then
+#			msg2 "$(gettext "Adding %s file...")" "$orig"
+#			if ! cp "$startdir/${!orig}" "$dest"; then
+#				error "$(gettext "Failed to add %s file to package.")" "$orig"
+#				exit $E_MISSING_FILE
+#			fi
+#			chmod 644 "$dest"
+#		fi
+#	done
+
+	# tar it up
+	local fullver=$(get_full_version)
+	local pkg_file="$PKGDEST/${pkgname}-${fullver}-${pkgarch}${PKGEXT}"
+	local ret=0
+
+	[[ -f $pkg_file ]] && rm -f "$pkg_file"
+#	[[ -f $pkg_file.sig ]] && rm -f "$pkg_file.sig"
+
+	# ensure all elements of the package have the same mtime
+	find . -exec touch -h -d @$SOURCE_DATE_EPOCH {} +
+  dpkg-deb -b . "${pkg_file}"
+# msg2 "$(gettext "Generating .MTREE file...")"
+#	list_package_files | LANG=C bsdtar -cnf - --format=mtree \
+#		--options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
+#		--null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE
+#	touch -d @$SOURCE_DATE_EPOCH .MTREE
+#
+#	msg2 "$(gettext "Compressing package...")"
+#	# TODO: Maybe this can be set globally for robustness
+#	shopt -s -o pipefail
+#	list_package_files | LANG=C bsdtar --no-fflags -cnf - --null --files-from - |
+#		compress_as "$PKGEXT" > "${pkg_file}" || ret=$?
+#
+#	shopt -u -o pipefail
+
+	if (( ret )); then
+		error "$(gettext "Failed to create package file.")"
+		exit $E_PACKAGE_FAILED
+	fi
 }
 
 create_package_arch() {
